# Generated by Django 3.2.19 on 2023-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230622_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
