# Generated by Django 3.2.19 on 2023-06-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
