# Generated by Django 3.2.19 on 2023-06-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20230607_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Burger',
        ),
        migrations.RenameModel(
            old_name='Burgers',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='Sides',
            new_name='Side',
        ),
    ]
