# Generated by Django 3.2.19 on 2023-06-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20230608_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='side',
            options={'ordering': ['created']},
        ),
    ]
