# Generated by Django 3.2.19 on 2023-06-16 15:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_burger_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='alt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='burger',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlnmcty8k/image/upload/v1686923761/burger-hamburger-cheeseburger-full-nbg_innxx5.png', max_length=255, verbose_name='image'),
        ),
    ]
