# Generated by Django 3.2.19 on 2023-06-16 15:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20230616_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
