# Generated by Django 3.2.19 on 2023-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_burger_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
