# Generated by Django 3.2.19 on 2023-06-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
