# Generated by Django 3.2.19 on 2023-06-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_rename_order_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
